"""remove_step_name_from_workflow_steps

Revision ID: 0174f7457d94
Revises: 16685ad1ec39
Create Date: 2026-05-17 00:58:54.590232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0174f7457d94'
down_revision: Union[str, Sequence[str], None] = '16685ad1ec39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('workflow_steps', 'step_name', nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
