"""add_process_type_is_active_to_workflow

Revision ID: 16685ad1ec39
Revises: c1f6076aa349
Create Date: 2026-05-16 23:31:35.664272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16685ad1ec39'
down_revision: Union[str, Sequence[str], None] = 'c1f6076aa349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Önce enum tipini oluştur
    processtype = sa.Enum('PURCHASE_REQUEST', 'SUPPLIER_APPROVAL', 'CONTRACT_APPROVAL', 'ORDER_APPROVAL', name='processtype')
    processtype.create(op.get_bind())

    # Sonra kolonları ekle
    op.add_column('workflows', sa.Column('process_type', processtype, nullable=True))
    op.add_column('workflows', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))

    # Mevcut kayıtlar için default değer ver
    op.execute("UPDATE workflows SET process_type = 'PURCHASE_REQUEST' WHERE process_type IS NULL")

    # Nullable=False yap
    op.alter_column('workflows', 'process_type', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'is_active')
    op.drop_column('workflows', 'process_type')
    # ### end Alembic commands ###
