"""add_role_to_users

Revision ID: be84249c3f36
Revises: 0174f7457d94
Create Date: 2026-05-20 03:27:17.381567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be84249c3f36'
down_revision: Union[str, Sequence[str], None] = '0174f7457d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # role kolonu zaten veritabanında var, mevcut kullanıcılara EMPLOYEE rolü ver
    op.execute("UPDATE users SET role = 'EMPLOYEE' WHERE role IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_steps', 'step_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
